#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bridge-utils
Version  : 1.7
Release  : 19
URL      : https://mirrors.kernel.org/pub/linux/kernel/people/shemminger/bridge-utils/bridge-utils-1.7.tar.xz
Source0  : https://mirrors.kernel.org/pub/linux/kernel/people/shemminger/bridge-utils/bridge-utils-1.7.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: bridge-utils-bin = %{version}-%{release}
Requires: bridge-utils-license = %{version}-%{release}
Requires: bridge-utils-man = %{version}-%{release}

%description
This utility is DEPRECATED. No new features will ever be added.
Instead use the bridge command from the iproute2 package which
supports more features.

%package bin
Summary: bin components for the bridge-utils package.
Group: Binaries
Requires: bridge-utils-license = %{version}-%{release}

%description bin
bin components for the bridge-utils package.


%package license
Summary: license components for the bridge-utils package.
Group: Default

%description license
license components for the bridge-utils package.


%package man
Summary: man components for the bridge-utils package.
Group: Default

%description man
man components for the bridge-utils package.


%prep
%setup -q -n bridge-utils-1.7
cd %{_builddir}/bridge-utils-1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604537701
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1604537701
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bridge-utils
cp %{_builddir}/bridge-utils-1.7/COPYING %{buildroot}/usr/share/package-licenses/bridge-utils/9a2473b1af68a99d91b786625fcf075c2b24c35f
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/brctl

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bridge-utils/9a2473b1af68a99d91b786625fcf075c2b24c35f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/brctl.8
