#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bridge-utils
Version  : 1.6
Release  : 12
URL      : https://www.kernel.org/pub/linux/utils/net/bridge-utils/bridge-utils-1.6.tar.xz
Source0  : https://www.kernel.org/pub/linux/utils/net/bridge-utils/bridge-utils-1.6.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: bridge-utils-bin
Requires: bridge-utils-doc
Patch1: bridge-utils-1.5-linux_3.8_fix-1.patch

%description
This version of the bridge utilities is for Linux 2.4 and 2.6,
it uses the sysfs interface if possible on Linux 2.6.

%package bin
Summary: bin components for the bridge-utils package.
Group: Binaries

%description bin
bin components for the bridge-utils package.


%package doc
Summary: doc components for the bridge-utils package.
Group: Documentation

%description doc
doc components for the bridge-utils package.


%prep
%setup -q -n bridge-utils-1.6
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1493401589
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1493401589
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/brctl

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
