#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bridge-utils
Version  : 1.5
Release  : 11
URL      : https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5.tar.gz
Source0  : https://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: bridge-utils-doc
Patch1: bridge-utils-1.5-linux_3.8_fix-1.patch

%description
This version of the bridge utilities is for Linux 2.4 and 2.6,
it uses the sysfs interface if possible on Linux 2.6.

%package doc
Summary: doc components for the bridge-utils package.
Group: Documentation

%description doc
doc components for the bridge-utils package.


%prep
%setup -q -n bridge-utils-1.5
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489102010
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1489102010
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
